config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item= Item.new
  end

  def create
    Item.create(item_params)
    redirect_to items_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:nom_epice, :info, :img_url)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-sm-8 col-md-4 offset-sm-2 offset-md-4">

<h1> Les épices </h1>
</div>
<h3><%= link_to'Ajout ton épice', new_item_path %></h3>

  <div class="container">
    <div class="div">
      <% @items.each do |item| %>
        <div class="card_category">
          <%# <h2><%= link_to famille.name, famille_items_path(famille) %>
          <h2><%= link_to item.nom_epice, item_path(item)%></h2>
          <p><%= item.info %></p>
          <img src="<%= item.img_url %>", width="200" , height="200">

          <h2>Prix</h2>
          <h4><%= item.prix %>€</h4>
          <%= link_to "Supprimer", item_path(item), method: :delete, data: {confirm: "tu es sure?"} %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="row mt-5">

<h1>Ajout ton épice</h1>

      <%= form_for @item do |f| %>

				<%= f.label :nom_epice, "1 -" %>
				<%= f.text_field :nom_epice, placeholder: "Ajout le nom" %>

				<%= f.label :info, "2 -" %>
				<%=f.text_field :info, placeholder: "Ajout des informations" %>

				<%= f.label :prix, "3 -" %>
				<%=f.number_field :prix, placeholder: "Ajout ton prix" %>

				<%= f.label :img_url, "4 -" %>
				<%=f.text_field :img_url, placeholder: "URL de l'image" %>

				<%= f.submit :Création %>

			<% end %>

<%= link_to "Retour à la liste", items_path %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-sm-8 col-md-4 offset-sm-2 offset-md-4">

    <h1><%= @item.nom_epice %></h1>
      <p><%= @item.info %></p>
      <img src="<%= @item.img_url %>", width="200" , height="200">

      <h2>Prix</h2>
      <h4><%= @item.prix %>€</h4>

      <h2>Poids</h2>
        <select>
          <option>25g</option>
          <option>50g</option>
          <option>75g</option>
        </select>

      <h2>Quantité</h2>
        <select>
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
        </select>

<%# <%= link_to "Retour à la liste", items_path %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EpicesUser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to items_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.epicesdumonde.com/img/c/12-0_thumb.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/96231434?s=400&u=4995cef9a32dbd3fd633fdabef23f7885e8e2ca8&v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>